extends: "eslint:recommended"

env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 9 # to use async / await
  sourceType: 'module'

plugins:
  - jsdoc
  - ava

settings:
  jsdoc:
    addtionalTagNames:
      customTags:
        - swagger
        - extends

rules:
  no-unused-vars: warn
  no-console: 0
